# Generated by Django 2.2.10 on 2020-09-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20200901_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
