# Generated by Django 2.2.10 on 2020-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20200901_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='slug',
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
