# Generated by Django 2.2.10 on 2020-09-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20200901_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
