# Generated by Django 2.2.10 on 2020-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_remove_phone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
