# Generated by Django 2.2.10 on 2020-09-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Название модели')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('os', models.TextField(blank=True, null=True, verbose_name='Операционная система')),
                ('ram', models.IntegerField(null=True, verbose_name='Оперативная память')),
                ('ppi', models.IntegerField(null=True, verbose_name='Пикселей на дюйм')),
                ('d_camera', models.BooleanField(null=True, verbose_name='Двойная камера')),
                ('cpu', models.TextField(blank=True, null=True, verbose_name='Процессор')),
                ('screen', models.TextField(blank=True, null=True, verbose_name='Разрешение экрана')),
            ],
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Phones', verbose_name='Название модели')),
            ],
        ),
    ]
