# Generated by Django 2.2.10 on 2020-09-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsung',
            name='compass',
            field=models.TextField(null=True, verbose_name='компас'),
        ),
        migrations.AddField(
            model_name='samsung',
            name='gyroscope',
            field=models.TextField(null=True, verbose_name='гироскоп'),
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.TextField(blank=True, null=True, verbose_name='FM-радио')),
                ('recorder', models.TextField(blank=True, null=True, verbose_name='Диктофон')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Phones', verbose_name='Название модели')),
            ],
        ),
    ]
