# Generated by Django 2.2.10 on 2020-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20200908_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='ppi',
            field=models.CharField(max_length=25, null=True, verbose_name='Пикселей на дюйм'),
        ),
    ]
