# Generated by Django 2.2.10 on 2020-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200917_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.ManyToManyField(related_name='teachers', to='school.Student', verbose_name='Студенты'),
        ),
    ]
