# Generated by Django 2.2.10 on 2020-09-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200921_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(related_name='divs', through='articles.Elements', to='articles.Article'),
        ),
    ]
