# Generated by Django 2.2.13 on 2020-09-25 12:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200925_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
